### ISSUE TITLE
Sign-in direct URL access does not work after logout (useraccounts)

### ISSUE THREAD

**Issue by jirkadev** [brettle/meteor-accounts-deluxe#3]
Hi,
I have a problem with my app and I found out that it behaves same in your example http://brettle-accounts-demo.meteor.com/

To reproduce an error:
1. I enter URL http://brettle-accounts-demo.meteor.com/sign-in
2. I switch to useraccounts
3. I press 'Sign In' button I Sign In with Google
4. I press 'Sign Out' button
5. I directly enter URL http://brettle-accounts-demo.meteor.com/sign-in and I am redirected to root '/' instead of Sign-in page

I got no redirect error with `useraccounts` package without `brettle:accounts-deluxe` package

I have same error when I install just `brettle:accounts-anonymous-auto` and `brettle:accounts-patch-ui`

Otherwise great package, Thank you

**Comment by brettle** [comment]
Thanks for the bug report and sorry for the delayed response. I just published a fix for this in version 0.1.9 of `brettle:accounts-patch-ui` (on which `brettle:accounts-deluxe` depends).
