### ISSUE TITLE
Beta invite system with accounts-anonymous?

### ISSUE THREAD

**Issue by t3db0t** [brettle/meteor-accounts-deluxe#4]
I've been trying to wrap my head around how `accounts-anonymous` works, and see if it might solve a big problem: beta invites that accommodate OAuth services (as opposed to only `accounts-password`, which is how most/all? beta invite systems for Meteor seem to work so far).  

The flow would be:
- user is invited by email, entry added in invites collections
- invite url in email goes to a specific `acceptInvite` route
- only at that route/template can a new account (of any type) be created
- however, the normal login popover must be available anywhere at any time for already registered users to use; it just can't allow new account creation unless it's being redeemed via `acceptInvite`.

What accounts-anonymous would do is:
- when the `acceptInvite` route is reached, set an `allowRegistration` flag in the anonymous user record
- when the `validateNewUser` callback is reached, check the `user` param that's passed in for that flag.

Anyway—I haven't tested this yet, but I want to ASAP.  I'm writing this here to see if this makes sense from your perspective and see if it could be a valuable addition to the `accounts-deluxe` suite.  Seems like minimal impact.

**Comment by brettle** [comment]
Makes sense to me and it sounds like a useful package. Not sure if I'd add it to accounts-deluxe. It would probably depend on whether it would add a dependency on a router.

**Comment by t3db0t** [comment]
After I wrote that I realized it makes more sense as a distinct package that depends on `accounts-deluxe`.  Yes, I'd have to figure out how router dependency would work.

One question that has come up—when the `acceptInvite` route is reached, it will need to check if that invite hash already has a user account associated to it (i.e. an anonymous one), and if so, use that user account instead of a _new_ anonymous one.  Is there any way to do this?

**Comment by t3db0t** [comment]
Is there any kind of `onBeforeCreateAnonymousUser` callback, for instance, where I could run a test first to decide what user to use?

**Comment by brettle** [comment]
After thinking about this some more, it's not clear that `accounts-anonymous` is the right solution for you, but you can use it as a model for achieving what you want. Here is (untested!) code modeled after `accounts-anonymous` which might do what you want.
1. In your `acceptInvite` route, in client code, call a new method, say `AccountsInvited.login(invitationHash)`, that takes the invitation hash and passes it to `Accounts.callLoginMethod()` as `profile.invitationHash`.

``` js
  AccountsInvited.login = function (invitationHash, callback) {
  callback = callback || function () {};
  if (Meteor.userId()) {
    callback(new Meteor.Error(AccountsAnonymous._ALREADY_LOGGED_IN_ERROR,
      "You can't login anonymously while you are already logged in."));
    return;
  }
  Accounts.callLoginMethod({
    methodArguments: [{
      invitationHash: invitationHash
    }],
    userCallback: function (error) {
      if (error) {
        if (callback) { callback(error); }
      } else {
        if (callback) { callback(); }
      }
    }
  });
};
```
1. In server code, register a login handler that looks for an existing user with the same hash. If it doesn't find one, it creates one. It then returns the new/existing user's id which causes the user to be logged in.

``` js
Accounts.registerLoginHandler("invitationHash", function(options) {
  if (!options || !options.invitationHash || Meteor.userId()) {
    return undefined;
  }

  var userId;
  var existingUser = Meteor.users.findOne({ 'services.invitationHash.hash': invitationHash);
  if (existingUser) {
    userId = existingUser._id;
  } else {
    newUserId = Accounts.insertUserDoc(options, {
      services: {
        invitationHash: {
          hash: invitationHash
        }
    });
  }
  return {
    userId: userId
  };
});
```

**Comment by t3db0t** [comment]
Ah ok—interesting! I wasn't aware of those Accounts APIs. So if I understand correctly—regular logins outside of the `acceptInvitation` route would use `validateNewUser` to check for the `invitationHash` property or similar, hence rejecting new logins outside of that route.

Thanks so much for your thoughts, I will try this out as soon as I can!

**Comment by t3db0t** [comment]
I got this working—I see now; you'll appear as "logged in" because it's going through the `Accounts` system (I could leave out the login buttons on this template or use `patch-ui` maybe ;)).  Now all I need, I think, is a way to add services (Oauth or accounts-password) to the new user account (perhaps with `brettle:accounts-add-service`, why not!).  I'm gonna flesh this out and perhaps package-ize it. :D

**Comment by t3db0t** [comment]
Well, I've gotten really far with this: https://github.com/t3db0t/beta-invite-test

However, after all this, I find that when I go to add a login service (i.e. Facebook), the validation callbacks show the proposed new user record/login attempt, NOT the one previously created by the 'anonymous' user login method.  Argh. Gotta think about this.

**Comment by brettle** [comment]
brettle:accounts-add-service might fix that for you. If not, you should be able to use brettle:accounts-multiple.

**Comment by t3db0t** [comment]
Aha—`accounts-multiple` is EXACTLY what I needed. Thank you!

**Comment by t3db0t** [comment]
I spoke too soon. `accounts-multiple` gives me a perfect way to validate in the case of the `acceptInvitation` route, but I still need a way to reject validation everywhere else.  I can use `validateNewUser`, but then I have no way of telling where the request is coming from, and I'm back to square one.  I could use a method to set and unset the `validateSwitch` callback, but that feels super kludgy.  I really just need a callback from `accounts-multiple` that's _only called_ when there's a login attempt with no existing user.  I'm probably missing something simple but I need sleep ;)

**Comment by t3db0t** [comment]
Proposal: add an additional `noUserCallback` callback that gets called after [detecting no userId](https://github.com/brettle/meteor-accounts-multiple/blob/master/accounts-multiple-server.js#L88).  I can try this out, just not sure when.

**Comment by t3db0t** [comment]
OK. Sorry for all this noise.  I finally have a working system: https://github.com/t3db0t/beta-invite-test

I had to modify `accounts-multiple` to provide an additional `onNoAttemptingUser` callback: https://github.com/t3db0t/meteor-accounts-multiple/blob/master/accounts-multiple-server.js#L93

If you're not totally sick of this thread, I'd love for you to have a look and tell me I'm not crazy.

**Comment by t3db0t** [comment]
OK, here's my (mostly) final package: https://github.com/t3db0t/meteor-accounts-invite

Thanks again for all your help!
