### ISSUE TITLE
Where is Documentation?

### ISSUE THREAD

**Issue by jmwierzbicki** [brettle/meteor-accounts-deluxe#5]
Well, im using Your plugin, and its great so far, but i have constantly problems, that i cannot find methods You provide - for example i cant find anywhere, how to check if account is guest serverside...

**Comment by brettle** [comment]
`brettle:accounts-deluxe` just bundles several other packages. Most of the documentation is in the `README.md` files associated with those other packages. One of the packages is `brettle:accounts-login-state`. Per [its documentation](brettle/meteor-accounts-login-state/blob/master/README.md), you can call `LoginState.signedUp(user)` on the server to determined if `user` is a guest. If you don't pass `user`, the current user is assumed.

**Comment by jmwierzbicki** [comment]
Awesome. Thanks!
