### ISSUE TITLE
Compatibility problems with Blaze and Flow Router

### ISSUE THREAD

**Issue by johngonzalez** [brettle/meteor-accounts-deluxe#6]
Hello, I love your package and congratulations for excellent demo documentation, investigation and coding.
I have next problem using **Meteor 1.3.4.1**.

1) If I install the package using:
`meteor add meteor add brettle:accounts-deluxe`
I get compatibility problems with Flow-Router:

```
=> Errors while adding packages:             

While selecting package versions:
error: Potentially incompatible change required to top-level dependency:
kadira:flow-router 2.7.0, was 2.12.1.
Constraints on package "kadira:flow-router":
* kadira:flow-router@=2.7.0 || =2.6.2 || =2.4.0 || =2.3.0 || =2.2.0 <-
brettle:accounts-patch-ui 0.1.3 <- brettle:accounts-deluxe 0.2.1

To allow potentially incompatible changes to top-level dependencies, you must
pass --allow-incompatible-update on the command line.
```

So I made meteor recommendation, but Flow-Router downgrade from 2.12.1 and accounts-deluxe to 0.2.1.

2) Now if I install specifically 0.2.2 version using:
`meteor add meteor add brettle:accounts-deluxe@0.2.2`
I get compatibility problems with Blaze:

```
 => Errors while adding packages:             

While selecting package versions:
error: Conflict: Constraint blaze@=2.1.5 || =2.1.4 || =2.1.3 || =2.1.2 ||
=2.1.1 || =2.1.0 || =2.1.6 || =2.1.7 is not satisfied by blaze 2.1.8.
Constraints on package "blaze":
* blaze@=2.1.8 <- top level
* blaze@2.1.8 <- spacebars 1.0.12 <- blaze-html-templates 1.0.4
* blaze@2.1.7 <- ui 1.0.11 <- blaze-html-templates 1.0.4
* blaze@2.1.8 <- launch-screen 1.0.12 <- mobile-experience 1.0.4
* blaze@2.1.7 <- blaze-html-templates 1.0.4
* blaze@2.1.8 <- templating 1.1.12_1 <- blaze-html-templates 1.0.4
* blaze@2.1.8 <- accounts-base 1.2.8 <- accounts-password 1.1.11
* blaze@2.1.3 <- alanning:roles 1.2.15
* blaze@2.1.3 <- meteorhacks:ssr 2.2.0
* blaze@=2.1.5 || =2.1.4 || =2.1.3 || =2.1.2 || =2.1.1 || =2.1.0 || =2.1.6 ||
=2.1.7 <- brettle:accounts-patch-ui 0.1.12 <- brettle:accounts-deluxe 0.2.2
```

Thanks for any collaboration, I want to use this package in my project

**Comment by johngonzalez** [comment]
I have a insight that maybe can help! Because I don't need auth services as facebook or google, I only installed the following packages:

```
meteor add brettle:accounts-anonymous
meteor add brettle:accounts-login-state
meteor add brettle:accounts-anonymous-auto 
```

With these, meteor doesn't throw compatibility errors :)

I don't close this issue because the original problem persists with _meteor-accounts-deluxe_. Thanks

**Comment by brettle** [comment]
Thanks for the bug report. This is now fixed with the release of brettle:accounts-patch-ui 0.1.13.
